title: "[Pattern Documentation Request] "
labels: ["ROSES Idea"]
body:
  - type: markdown
    attributes:
      value: |
        ## F Prime Pattern Documentation Request

        Please use this form to submit an F Prime pattern you would like to see documented.

        This work is funded through a [NASA ROSES grant](https://github.com/nasa/fprime/discussions/3041).
        
        > [!TIP]
        > The above **Title** may be the only thing the community sees when voting on your pattern.

        ### Instructions
           1. Title: **Summarize** the pattern. Be as clear and concise as possible.
           2. Pattern: Describe **what** you want documented. 
           3. Rationale: (Optional) Describe **why** you want it documented.
  - type: textarea
    id: pattern
    attributes:
      label: Pattern
      description: "Describe what you want documented in F Prime"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Describe the **Pattern** without trying to sell it. Describe what you need.
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: "(Optional) Describe why you want it documented. Sell it to the community."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > [!TIP]        
        > Use the **Rationale** to sell your idea to the community. Describe why you need this.
